# Generated by Django 4.1.6 on 2023-02-27 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_post_review_product_remove_product_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_date',
        ),
    ]
